"""Add kaggle credentials to user

Revision ID: cf3ca21b3e89
Revises: 2a310ff50947
Create Date: 2026-06-29 22:40:44.565666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf3ca21b3e89'
down_revision: Union[str, Sequence[str], None] = '2a310ff50947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_kaggle_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('encrypted_kaggle_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_kaggle_key')
    op.drop_column('users', 'encrypted_kaggle_username')
    # ### end Alembic commands ###
