"""Add MLExperimentSession

Revision ID: ea9fbebdb61b
Revises: cf3ca21b3e89
Create Date: 2026-06-30 05:20:53.074877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea9fbebdb61b'
down_revision: Union[str, Sequence[str], None] = 'cf3ca21b3e89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_experiment_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('hypothesis', sa.String(), nullable=False),
    sa.Column('plan_json', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('findings_json', sa.String(), nullable=True),
    sa.Column('report_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_experiment_sessions_id'), 'ml_experiment_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ml_experiment_sessions_id'), table_name='ml_experiment_sessions')
    op.drop_table('ml_experiment_sessions')
    # ### end Alembic commands ###
