"""Add DataCleaningSession

Revision ID: fb123abc456
Revises: 7dc398ac6669
Create Date: 2026-07-19 08:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fb123abc456'
down_revision = '7dc398ac6669'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_cleaning_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('dataset_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('cleaned_dataset_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('instructions', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cleaned_dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_cleaning_sessions_id'), 'data_cleaning_sessions', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_data_cleaning_sessions_id'), table_name='data_cleaning_sessions')
    op.drop_table('data_cleaning_sessions')
    # ### end Alembic commands ###
