import TopNav from '../components/layout/TopNav';
import Footer from '../components/layout/Footer';

export default function Terms() {
  return (
    <div className="min-h-screen bg-void text-ink font-sans flex flex-col">
      <TopNav />
      <main className="flex-1 max-w-4xl mx-auto px-6 py-24">
        <h1 className="font-mono text-4xl md:text-5xl text-ink mb-8 tracking-tighter">Terms of Service</h1>
        
        <div className="space-y-8 text-muted leading-relaxed">
          <section>
            <h2 className="font-mono text-2xl text-ink mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing and using Darelm ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-2xl text-ink mb-4">2. Acceptable Use</h2>
            <p>
              You agree to use the Platform only for lawful data analysis and machine learning purposes. You may not:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Upload malicious code, viruses, or attempt to breach our secure sandbox environments.</li>
              <li>Upload sensitive personal data (e.g., SSNs, protected health information) unless you have the explicit legal right and consent to do so.</li>
              <li>Attempt to reverse engineer the AI agents, the platform architecture, or our proprietary intelligence engine.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-mono text-2xl text-ink mb-4">3. Intellectual Property</h2>
            <p>
              Darelm retains all rights, title, and interest in the Platform, its UI/UX, AI agent architectures, and execution environments. 
              However, you retain all intellectual property rights to the raw data you upload and the specific reports, models, and Python scripts generated by our agents during your sessions.
            </p>
          </section>

          <section>
            <h2 className="font-mono text-2xl text-ink mb-4">4. Limitation of Liability</h2>
            <p>
              While our AI agents strive for high accuracy, machine learning models can produce unexpected or hallucinatory results. 
              Darelm provides these tools "as is" and is not liable for business decisions, financial losses, or damages incurred by relying solely on automated AI insights. We recommend human oversight for critical decisions.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
